tcpdf:
    param:
#        orientation: 'P'
#        unit: 'mm'
#        format: 'A4'
#        unicode: true
#        encoding: 'UTF-8'
#        diskcache: false
#        pdfa: false
    config:
#        k_path_main: '%kernel.root_dir%/../vendor/tecnickcom/tcpdf/'
#        k_path_url: '%kernel.root_dir%/../vendor/tecnickcom/tcpdf/'
#        k_path_fonts: '%kernel.root_dir%/../vendor/tecnickcom/tcpdf/fonts/'
#        k_path_images: '%kernel.root_dir%/../vendor/tecnickcom/tcpdf/examples/images/'
#        k_path_cache: '%kernel.cache_dir%/tcpdf'
#        k_path_url_cache: '%kernel.cache_dir%/tcpdf'
#        k_blank_image: '%kernel.root_dir%/../vendor/tecnickcom/tcpdf/examples/images/_blank.png'
#        k_cell_height_ratio: 1.25
#        k_title_magnification: 1.3
#        k_small_ratio: 2/3
#        k_thai_topchars: true
#        k_tcpdf_calls_in_html: false
#        k_tcpdf_external_config: true
#        k_timezone: 'UTC'
#
#        head_magnification: 1.1
#        pdf_header_logo: ''
#        pdf_header_logo_width: 0
#        pdf_page_format: 'A4'
#        pdf_page_orientation: 'P'
#        pdf_creator: 'TCPDF'
#        pdf_author: 'TCPDF'
#        pdf_header_title: ''
#        pdf_header_string: ''
#        pdf_unit: 'mm'
#
#        pdf_margin_header: 5
#        pdf_margin_footer: 10
#        pdf_margin_top: 27
#        pdf_margin_bottom: 25
#        pdf_margin_left: 15
#        pdf_margin_right: 15
#
#        pdf_font_name_main: 'helvetica'
#        pdf_font_size_main: 10
#        pdf_font_name_data: 'helvetica'
#        pdf_font_size_data: 8
#        pdf_font_monospaced: 'courier'
#
#       pdf_image_scale_ratio: 1.25