parameters:
    vladmeh.tcpdf.class: Vladmeh\Bundle\TCPDFBundle\Controller\TCPDFController

services:
    tcpdf:
        class: "%vladmeh.tcpdf.class%"
        arguments: []
        public: true

    Vladmeh\Bundle\TCPDFBundle\Controller\TCPDFController: ~