language: php

sudo: false
cache:
    directories:
        - $HOME/.composer/cache/files

php:
  - 7.1
  - 7.2
  - nightly
  - hhvm

matrix:
  allow_failures:
    - php: nightly
    - php: hhvm

before_script:
  - travis_retry composer self-update
  - travis_retry composer update --no-interaction --prefer-source

script:
  - composer validate --strict --no-check-lock
  - phpunit